name: CI for book
on:
  push:
    branches: [ main ]
  pull_request:
    paths-ignore:
      - "README.md"
      - "frontend/**"

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Cache dependencies
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable

      - name: Install cargo-related tool
        uses: taiki-e/install-action@9e1e5806d4a4822de933115878265be9aaa786d9 # v2.82.2
        with:
          tool: nextest,cargo-make,cargo-machete

      - name: Check unused dependencies
        run: cargo machete

      - name: Tests compile
        run: cargo make test-ci --no-run --locked

      - name: Test
        run: cargo make test-ci

      - name: Clippy
        run: cargo make clippy-ci -- -Dwarnings

      - name: Rustfmt
        run: cargo make fmt -- --check
